---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: app-service-dev
  labels:
    app: react-app-dev
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30100
  selector:
    app: react-app-dev

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: react-app-dev
  labels:
    app: react-app-dev
spec:
  selector:
    matchLabels:
      app: react-app-dev
  strategy:
    type: Recreate
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 0
  template:
    metadata:
      labels:
        app: react-app-dev
    spec:
      containers:
        - name: react-app-dev
          image: alexeyguskov/react-app:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "300Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "200m"
          volumeMounts:
          - name: app-persistent-volume
            mountPath: /data
      volumes:
      - name: app-persistent-volume
        persistentVolumeClaim:
          claimName: pvc-app-dev
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: dev
  name: app-hpa-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react-app-dev
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70