---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-app-dev
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Gi
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dev
  name: pvc-app-dev
  labels:
    app: pvc-app-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-app-prod
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Gi
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: prod
  name: pvc-app-prod
  labels:
    app: pvc-app-prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi