#!/usr/bin/env groovy

Pipeline {
    agent { 
        docker {
            image 'node'
            args '-u root'
        }
    }

    environment {
        APP_PATH = "/app"
    }
    stages {
        stage('Build') {
            steps{
              dir(APP_PATH){
                sh "npm install"
                }
              }
            }
            steps{
              dir(APP_PATH) {
                sh "npm run lint"
              }
            }  
    }
}