#!/usr/bin/env groovy
pipeline {
  agent any
    
  tools {nodejs "18.0.0"}
    
  stages {
        
    stage('Git') {
      steps {
        git 'https://github.com/GuskovAlexey/test'
      }
    }
     
    stage('Build') {
      steps {
        dir("/app"){
            sh 'npm install'
        }
      }
    }  
    
            
    stage('Test') {
      steps {
        sh 'node run test'
      }
    }
  }
}